# Generated by Django 2.0.9 on 2018-10-23 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misperris', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoptado',
            name='id',
        ),
        migrations.AddField(
            model_name='adoptado',
            name='idPerro',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
