# Generated by Django 2.0.9 on 2018-10-23 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misperris', '0002_auto_20181023_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptado',
            name='fotografia',
            field=models.ImageField(upload_to=''),
        ),
    ]
