# Generated by Django 2.0.9 on 2018-10-26 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misperris', '0003_auto_20181023_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptado',
            name='estado',
            field=models.CharField(choices=[('ADOPTADO', 'ADOPTADO'), ('RESCATADO', 'RESCATADO'), ('DISPONIBLE', 'DISPONIBLE')], max_length=10),
        ),
    ]
