# Generated by Django 2.0.9 on 2018-10-24 20:10

from django.db import migrations, models
import misperris.validators


class Migration(migrations.Migration):

    dependencies = [
        ('misperris', '0004_auto_20181024_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptante',
            name='run',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, validators=[misperris.validators.run_validation]),
        ),
    ]
