# Generated by Django 2.0.9 on 2018-10-24 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misperris', '0005_auto_20181024_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptante',
            name='telefono',
            field=models.CharField(max_length=9),
        ),
    ]
