# Generated by Django 2.0.9 on 2018-10-25 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misperris', '0007_auto_20181025_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoptante',
            name='ciudad',
        ),
    ]
