# Generated by Django 2.0.9 on 2018-10-26 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misperris', '0004_auto_20181025_2157'),
        ('misperris', '0007_auto_20181025_1835'),
    ]

    operations = [
    ]
