# Generated by Django 2.0.9 on 2018-10-26 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misperris', '0008_merge_20181026_0006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoptante',
            name='ciudad',
        ),
    ]
