# Generated by Django 2.0.9 on 2018-10-28 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misperris', '0009_remove_adoptante_ciudad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoptado',
            name='idPerro',
        ),
        migrations.AddField(
            model_name='adoptado',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
